const releaseOrder = import("./types/orderTypes");

var moviesData = [
  {
    Id: 1,
    name: "Iron Man",
    releaseorder: 1,
    chronologicalorder: 3,
    phase: "Phase1",
    saga: "Infinity Saga",
    superhero: "Iron Man",
    trailerid: "8ugaeA-nMTc",
    order: "Chronological Order",
  },
  {
    Id: 2,
    name: "The Incredible Hulk",
    releaseorder: 2,
    chronologicalorder: 5,
    phase: "Phase1",
    saga: "Infinity Saga",
    superhero: "Hulk",
    trailerid: "O-f3TVN6BN8",
    order: "Release order",
  },

  {
    Id: 3,
    name: "Iron Man 2",
    releaseorder: 3,
    chronologicalorder: 4,
    phase: "Phase1",
    saga: "Infinity Saga",
    superhero: "Iron Man",
    trailerid: "BoohRoVA9WQ",
    order: "Release order",
  },
  {
    Id: 4,
    name: "Thor",
    releaseorder: 4,
    chronologicalorder: 6,
    phase: "Phase1",
    saga: "Infinity Saga",
    superhero: "Thor",
    trailerid: "JOddp-nlNvQ",
    order: "Release order",
  },

  {
    Id: 5,
    name: "Captain America: The First Avenger",
    releaseorder: 5,
    chronologicalorder: 1,
    phase: "Phase1",
    saga: "Infinity Saga",
    superhero: "Captain America",
    trailerid: "JerVrbLldXw",
    order: "Chronological Order",
  },

  {
    Id: 6,
    name: "The Avengers",
    releaseorder: 6,
    chronologicalorder: 7,
    phase: "Phase1",
    saga: "Infinity Saga",
    superhero: "Avengers",
    trailerid: "eOrNdBpGMv8",
    order: "Release order",
  },

  {
    Id: 7,
    name: "Iron Man 3",
    releaseorder: 7,
    chronologicalorder: 9,
    phase: "Phase2",
    saga: "Infinity Saga",
    superhero: "Iron Man",
    trailerid: "Ke1Y3P9D0Bc",
    order: "Release order",
  },
  {
    Id: 8,
    name: "Thor: The Dark World",
    releaseorder: 8,
    chronologicalorder: 8,
    phase: "Phase2",
    saga: "Infinity Saga",
    superhero: "Thor",
    trailerid: "jHFhZLJajlc",
    order: "Release order",
  },

  {
    Id: 9,
    name: "Captain America: The Winter Soldier",
    releaseorder: 9,
    chronologicalorder: 10,
    phase: "Phase2",
    saga: "Infinity Saga",
    superhero: "Captain America",
    trailerid: "tbayiPxkUMM",
    order: "Release order",
  },
  {
    Id: 10,
    name: "Guardians of the Galaxy",
    releaseorder: 10,
    chronologicalorder: 11,
    phase: "Phase2",
    saga: "Infinity Saga",
    superhero: "Gardians of the Galaxy",
    trailerid: "d96cjJhvlMA",
    order: "Release order",
  },
  {
    Id: 11,
    name: "Avengers: Age of Ultron",
    releaseorder: 11,
    chronologicalorder: 13,
    phase: "Phase2",
    saga: "Infinity Saga",
    superhero: "Avengers",
    trailerid: "P5iIPfNzj2o",
    order: "Release order",
  },

  {
    Id: 12,
    name: "Ant-Man",
    releaseorder: 12,
    chronologicalorder: 14,
    phase: "Phase2",
    saga: "Infinity Saga",
    superhero: "Ant Man",
    trailerid: "pWdKf3MneyI",
    order: "Release order",
  },

  {
    Id: 13,
    name: "Captain America: Civil War",
    releaseorder: 13,
    chronologicalorder: 15,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Captain America",
    trailerid: "FkTybqcX-Yo",
    order: "Release order",
  },

  {
    Id: 14,
    name: "Doctor Strange",
    releaseorder: 14,
    chronologicalorder: 19,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Doctor Strange",
    trailerid: "h7gvFravm4A",
    order: "Release order",
  },
  {
    Id: 15,
    name: "Guardians of the Galaxy 2",
    releaseorder: 15,
    chronologicalorder: 12,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Gardians of the Galaxy",
    trailerid: "pr7tDrwQ3t8&t",
    order: "Release order",
  },

  {
    Id: 16,
    name: "Spider-Man: Homecoming",
    releaseorder: 16,
    chronologicalorder: 17,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Spider Man",
    trailerid: "n9DwoQ7HWvI",
    order: "Release order",
  },
  {
    Id: 17,
    name: "Thor: Ragnarok",
    releaseorder: 17,
    chronologicalorder: 20,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Thor",
    trailerid: "JBxQ_XYQJhc",
    order: "Release order",
  },

  {
    Id: 18,
    name: "Black Panther",
    releaseorder: 18,
    chronologicalorder: 18,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Black Panther",
    trailerid: "xjDjIWPwcPU",
    order: "Release order",
  },

  {
    Id: 19,
    name: "Avengers: Infinity War",
    releaseorder: 19,
    chronologicalorder: 22,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Avengers",
    trailerid: "6ZfuNTqbHE8",
    order: "Release order",
  },

  {
    Id: 20,
    name: "Ant-Man and the Wasp",
    releaseorder: 20,
    chronologicalorder: 21,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Ant Man",
    trailerid: "8_rTIAOohas",
    order: "Release order",
  },
  {
    Id: 21,
    name: "Captain Marvel",
    releaseorder: 21,
    chronologicalorder: 2,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Captain Marvel",
    trailerid: "Z1BCujX3pw8",
    order: "Release order",
  },
  {
    Id: 22,
    name: "Avengers: Endgame",
    releaseorder: 22,
    chronologicalorder: 23,
    phase: "Phase3",
    saga: "Infinity Saga",
    superhero: "Avengers",
    trailerid: "TcMBFSGVi1c",
    order: "Release order",
  },
  {
    Id: 23,
    name: "Spider-Man: Far From Home",
    releaseorder: 23,
    chronologicalorder: 24,
    phase: "Phase3",
    saga: "Multiverse Saga",
    superhero: "Spider Man",
    trailerid: "Nt9L1jCKGnE",
    order: "Release order",
  },

  {
    Id: 24,
    name: "Black Widow",
    releaseorder: 24,
    chronologicalorder: 16,
    phase: "Phase4",
    saga: "Multiverse Saga",
    superhero: "Black Widow",
    trailerid: "ybji16u608U",
    order: "Release order",
  },

  {
    Id: 25,
    name: "Shang-Chi and the Legend of the Ten Rings",
    releaseorder: 25,
    chronologicalorder: 25,
    phase: "Phase4",
    saga: "Multiverse Saga",
    superhero: "Shang Chi",
    trailerid: "8YjFbMbfXaQ",
    order: "Release order",
  },

  {
    Id: 26,
    name: "Eternals",
    releaseorder: 26,
    chronologicalorder: 26,
    phase: "Phase4",
    saga: "Multiverse Saga",
    superhero: "Eternals",
    trailerid: "pWfjJ6bOy7w",
    order: "Release order",
  },

  {
    Id: 27,
    name: "Spider-Man: No Way Home",
    releaseorder: 27,
    chronologicalorder: 27,
    phase: "Phase4",
    saga: "Multiverse Saga",
    superhero: "Spider Man",
    trailerid: "JfVOs4VSpmA",
    order: "Release order",
  },

  {
    Id: 28,
    name: "Doctor Strange in the Multiverse of Madness",
    releaseorder: 28,
    chronologicalorder: 28,
    phase: "Phase4",
    saga: "Multiverse Saga",
    superhero: "Doctor Strange",
    trailerid: "aWzlQ2N6qqg",
    order: "Release order",
  },

  {
    Id: 29,
    name: "Thor: Love and Thunder",
    releaseorder: 29,
    chronologicalorder: 29,
    phase: "Phase4",
    saga: "Multiverse Saga",
    superhero: "Thor",
    trailerid: "Go8nTmfrQd8",
    order: "Release order",
  },

  {
    Id: 30,
    name: "Black Panther: Wakanda Forever",
    releaseorder: 30,
    chronologicalorder: 30,
    phase: "Phase4",
    saga: "Multiverse Saga",
    superhero: "Black Panther",
    trailerid: "_Z3QKkl1WyM",
    order: "Release order",
  },
];
export default moviesData;
